### ISSUE TITLE
Incidencias del proceso

### ISSUE THREAD

**Issue by wilnellia** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-wilnellia#1]
Tuve inconveniente al crear el Push, porque cuando estaba en la Terminal colocando el correo y el usuario, lo ingrese con la palabra Global, me di cuenta del error y lo corregí, , luego de varios intentos haciendo el Push, lo logre.

**Comment by geofis** [comment]
¡Perfecto! Cierro entonces el *issue*.
